=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://pcm.framework.org/service" 
xmlns="http://pcm.framework.org/service">
    
    <xs:element name="service-group" type="ServiceGroupType"/>
    
    <xs:complexType name="ServiceGroupType">
    	<xs:sequence>
		    <xs:element maxOccurs="unbounded" minOccurs="1" name="service" type="ServiceType"/>
		</xs:sequence>
	</xs:complexType>
    
	<xs:complexType name="profileAndNAmeInfo">
		<xs:attribute name="profile" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="ServiceType">
	  	<xs:complexContent>
	   		<xs:extension base="profileAndNAmeInfo">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="action" nillable="true" type="ActionType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ActionAttrsBaseType">
  		<xs:attribute name="id" type="xs:string"/>
  		<xs:attribute name="event" type="xs:string"/>
  		<xs:attribute name="submitError" type="xs:string"/>
  		<xs:attribute name="submitSucces" type="xs:string"/>
  		<xs:attribute name="transactional" type="xs:boolean"/>
  		<xs:attribute name="strategyPre" type="xs:string"/>
  		<xs:attribute name="strategy" type="xs:string"/>
  		<xs:attribute name="addressBook" type="xs:string"/>
  		<xs:attribute name="filterResults" type="xs:string"/>
  	</xs:complexType>
  
	<xs:complexType name="ActionType">
	  	<xs:complexContent>
	   		<xs:extension base="ActionAttrsBaseType">
		   		<xs:sequence>		    		
		    		<xs:element maxOccurs="unbounded" name="viewComponent" nillable="true" type="ComponentType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
  
  	<xs:complexType name="ComponentType">
  		<xs:sequence>
   			<xs:element maxOccurs="unbounded" minOccurs="0" name="form" nillable="true" type="FormType"/>
   			<xs:element maxOccurs="unbounded" minOccurs="0" name="grid" nillable="true" type="GridType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="FormAttrsBaseType">
		<xs:attribute name="align" type="xs:string"/>
		<xs:attribute name="columns" type="xs:integer"/>
		<xs:attribute name="title" type="xs:string"/>		
	</xs:complexType>
	
	<xs:complexType name="UserbuttonsType">
	  	<xs:sequence>
	  		<xs:element maxOccurs="unbounded" minOccurs="1" name="button" nillable="true" type="ButtonType"/>	    		
		 </xs:sequence>	   	
	</xs:complexType>
	
	
	<xs:complexType name="ButtonAttrsType">
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="onClick" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="ButtonType">
	  	<xs:complexContent>
	   		<xs:extension base="ButtonAttrsType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FormType">
	  	<xs:complexContent>
	   		<xs:extension base="FormAttrsBaseType">
		   		<xs:sequence>
		   			<xs:element maxOccurs="1" minOccurs="0" name="userbuttons" nillable="true" type="UserbuttonsType"/>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>	
	
	<xs:complexType name="GridAttrsBaseType">
		<xs:attribute name="title" type="xs:string"/>		
		<xs:attribute name="dependsOf" type="xs:string"/>
		<xs:attribute name="serviceRef" type="xs:string"/>
		<xs:attribute name="orderDirection" type="xs:string"/>
		<xs:attribute name="defaultOrderField" type="xs:string"/>
		<xs:attribute name="filterResults" type="xs:string"/>
		<xs:attribute name="eventsRegistered" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="GridType">
	  	<xs:complexContent>
	   		<xs:extension base="GridAttrsBaseType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FieldViewSetBase">
		<xs:attribute name="nameSpace" type="xs:string"/>
		<xs:attribute name="entitymodel" type="xs:string"/>
		<xs:attribute name="persist" type="xs:boolean"/>
		<xs:attribute name="order" type="xs:int"/>
	</xs:complexType>
	
	<xs:complexType name="FieldViewSetType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldViewSetBase">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="fieldset" nillable="true" type="FieldSetType"/>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="fieldView" nillable="true" type="FieldViewType"/>
		  		</xs:sequence>
	   		</xs:extension>	   		
	   	</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="FieldSetAttrBaseType">
		<xs:attribute name="legend" type="xs:string"/>
		<xs:attribute name="style" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="FieldSetType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldSetAttrBaseType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldView" nillable="true" type="FieldViewType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FieldViewTypeBase">
		<xs:attribute name="separator" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="required" type="xs:boolean"/>		
		<xs:attribute name="hidden" type="xs:boolean"/>
		<xs:attribute name="editable" type="xs:boolean"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="firstOption" type="xs:string"/>
		<xs:attribute name="size" type="xs:integer"/>
		<xs:attribute name="maxlength" type="xs:integer"/>
		<xs:attribute name="detailed" type="xs:boolean"/>
		<xs:attribute name="persistsIn" type="xs:string"/>
		<xs:attribute name="mappingTo" type="xs:integer"/>
		<xs:attribute name="relationalOpe" type="xs:string"/>
		<xs:attribute name="styleCss" type="xs:string"/>
		<xs:attribute name="formatted" type="xs:string"/>		
		<xs:attribute name="labelStyle" type="xs:string"/>	
		<xs:attribute name="default" type="xs:string"/>	
	</xs:complexType>
	
	<xs:complexType name="FieldViewType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldViewTypeBase">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="optionValues" nillable="true" type="OptionSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
  
  	<xs:complexType name="OptionSetType">
  		<xs:complexContent>
	   		<xs:extension base="OptionSetBase">
	   			<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="option" nillable="true" type="OptionType"/>
				</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
  		
  	</xs:complexType>
	
	<xs:complexType name="OptionSetBase">
  		<xs:attribute name="entitymodel" type="xs:string"/>
  		<xs:attribute name="descrMappingTo" type="xs:string"/>
  		<xs:attribute name="selectionMultiple" type="xs:boolean"/> 		  		
  		<xs:attribute name="codeField" type="xs:integer"/>
  		<xs:attribute name="editable" type="xs:boolean"/>
  	</xs:complexType>
  
    <xs:complexType name="OptionType">
    	<xs:complexContent>
	   		<xs:extension base="OptionBase">
	   		</xs:extension>
	   	</xs:complexContent>
  	</xs:complexType>
  	
  	<xs:complexType name="OptionBase">
  		<xs:attribute name="code" type="xs:string"/>
  		<xs:attribute name="title" type="xs:string"/>
  		<xs:attribute name="selected" type="xs:string"/>
  	</xs:complexType>
	  
	
</xs:schema>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/demos.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group 
	xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

	<service name="Demos" profile="ADMINISTRADOR, CONSULTOR_UTE">

	<action event="query" submitError="Demos.query"
		submitSucces="Demos.query">

		<viewComponent>

			<form columns="12" title="Demos - Gráficos - Mapas">
				
				<userbuttons>
				
					<button link="prjManager" id="mapaSpain" name="Demo con mapas (Spain)">
						<fieldViewSet nameSpace="mapaSpain">
							<fieldView name="highchart" hidden="true" value="mapspain"/>
							<fieldView name="entidadGrafico" hidden="true" value="peticiones"/>
							<fieldView name="orderBy" hidden="true" value="17"/>
							<fieldView name="fieldForGroupBy" type="select">
							<optionValues selectionMultiple="true">
									<option code="26" title="origen incidencia" selected="true"></option>
									<option code="7" title="origen solicitudes de mejora" selected="true"></option>
								</optionValues>
							</fieldView>
							<fieldView name="agregado" type="select">
								<optionValues>
									<option code="-1" title="peticiones"></option>
									<option code="28" title="coste estimado" selected="true"></option>
								</optionValues>
							</fieldView>
							<fieldView name="operation" type="select">
								<optionValues>
									<option code="SUM" title="agregados" selected="true"></option>
									<option code="AVG" title="medias"></option>
								</optionValues>
							</fieldView>
						</fieldViewSet>
					</button>
					
					<button link="prjManager" id="mapaEurope" name="Demo con mapas (Europe)">
						<fieldViewSet nameSpace="mapaEurope">
							<fieldView name="highchart" hidden="true" value="mapeurope"/>
							<fieldView name="entidadGrafico" hidden="true" value="peticiones"/>
							<fieldView name="orderBy" hidden="true" value="17"/>
							<fieldView name="fieldForGroupBy" type="select">
							<optionValues selectionMultiple="true">
									<option code="26" title="origen incidencia" selected="true"></option>
									<option code="7" title="origen solicitudes de mejora" selected="true"></option>
								</optionValues>
							</fieldView>
							<fieldView name="agregado" type="select">
								<optionValues>
									<option code="-1" title="peticiones"></option>
									<option code="28" title="coste estimado" selected="true"></option>
								</optionValues>
							</fieldView>
							<fieldView name="operation" type="select">
								<optionValues>
									<option code="SUM" title="agregados" selected="true"></option>
									<option code="AVG" title="medias"></option>
								</optionValues>
							</fieldView>
						</fieldViewSet>
					</button>
					
					<button link="prjManager" id="mapaWorld" name="Mapa World">
						<fieldViewSet nameSpace="mapaWorld">
							<fieldView name="highchart" hidden="true" value="mapworld"/>
							<fieldView name="entidadGrafico" hidden="true" value="peticiones"/>
							<fieldView name="orderBy" hidden="true" value="17"/>
							<fieldView name="fieldForGroupBy" type="select">
							<optionValues selectionMultiple="true">
									<option code="26" title="origen incidencia" selected="true"></option>
									<option code="7" title="origen solicitudes de mejora" selected="true"></option>
								</optionValues>
							</fieldView>
							<fieldView name="agregado" type="select">
								<optionValues>
									<option code="-1" title="peticiones"></option>
									<option code="28" title="coste estimado" selected="true"></option>
								</optionValues>
							</fieldView>
							<fieldView name="operation" type="select">
								<optionValues>
									<option code="SUM" title="agregados" selected="true"></option>
									<option code="AVG" title="medias"></option>
								</optionValues>
							</fieldView>
						</fieldViewSet>
					</button>
				</userbuttons>
				
				<fieldViewSet entitymodel="peticiones"	nameSpace="peticiones">
					<fieldView mappingTo="17" hidden="true" />
					<fieldView mappingTo="1" hidden="true" />
					<fieldView mappingTo="2" hidden="true" />
					<fieldView mappingTo="3" hidden="true" />
					<fieldView mappingTo="4" hidden="true" />
				</fieldViewSet>
				
				</form>
				
			</viewComponent>
			
		</action>
		
	</service>
	
</service:service-group>

=== pdulce/pcm/BI4ONGS/WebContent/WEB-INF/services/aplicativo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group 
	xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

    <service name="GestionApps" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="query" submitError="GestionApps.query"
			submitSucces="GestionApps.query">

			<viewComponent>

				<form columns="3" title="Consulta aplicativos">

					<fieldViewSet entitymodel="aplicativo"
						nameSpace="aplicativo">
						<fieldView mappingTo="2" size="20"/>
						<fieldView mappingTo="3" type="select" size="3" editable="true">
							<optionValues entitymodel="servicioUTE"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="6" type="select" size="3" editable="true">
							<optionValues entitymodel="tecnologia"
								descrMappingTo="2">
							</optionValues>
						</fieldView>			
						<fieldView separator="br" />
						<fieldView separator="br" />
						<fieldView mappingTo="4" size="30"/>
						<fieldView mappingTo="5" type="select" size="5" editable="true">						
							<optionValues selectionMultiple="true" entitymodel="aplicativo"
								descrMappingTo="5" codeField="5">
							</optionValues>							
						</fieldView>
						<fieldView mappingTo="7" type="checkbox">
							<optionValues selectionMultiple="true" entitymodel="aplicativo"
								descrMappingTo="7" codeField="7">
							</optionValues>
						</fieldView>

					</fieldViewSet>
				</form>

				<grid title="Listado aplicativos" orderDirection="asc" defaultOrderField="aplicativo.3" 
				eventsRegistered="update, create, delete">
					<fieldViewSet entitymodel="aplicativo"
						nameSpace="aplicativo">
						<fieldView mappingTo="1" hidden="true"/>
						<fieldView mappingTo="5" />
						<fieldView mappingTo="2" />
						<fieldView mappingTo="6" type="select" editable="false">
							<optionValues entitymodel="tecnologia"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="3" type="select" editable="false">
							<optionValues entitymodel="servicioUTE"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="7" type="text" editable="false"/>
					</fieldViewSet>
				</grid>

			</viewComponent>
		</action>

		<action event="delete" submitError="GestionApps.delete"
			submitSucces="GestionApps.query">

			<viewComponent>
				<form columns="3" title="Servicio">
					<fieldViewSet entitymodel="aplicativo" nameSpace="aplicativo">
						<fieldset legend="Aplicativo">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="5" editable="false" />
							<fieldView mappingTo="2" size="20" editable="false" />
							<fieldView mappingTo="6" type="select" editable="false">
							<optionValues entitymodel="tecnologia"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="3" type="select" editable="false">
								<optionValues entitymodel="servicioUTE"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" size="30" editable="false" />
							<fieldView mappingTo="7" type="radio" editable="false">
								<optionValues entitymodel="aplicativo"
									descrMappingTo="7" codeField="7">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
		
		<action event="create" submitError="GestionApps.create"
			submitSucces="GestionApps.create">

			<viewComponent>
				<form columns="3" title="Servicio">
					<fieldViewSet entitymodel="aplicativo" nameSpace="aplicativo">
						<fieldset legend="Aplicativo">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="5" editable="true" />
							<fieldView mappingTo="2" size="20" editable="true" />
							<fieldView mappingTo="6" type="select" editable="true">
								<optionValues entitymodel="tecnologia"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="3" type="select" editable="true">
								<optionValues entitymodel="servicioUTE"
									descrMappingTo="2" selectionMultiple="true">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" size="30" editable="true" />
							<fieldView mappingTo="7" type="check" editable="true">
								<optionValues entitymodel="aplicativo"
									descrMappingTo="7" codeField="7">
								</optionValues>
							</fieldView>							

							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
		
		<action event="update" submitError="GestionApps.update"
			submitSucces="GestionApps.update">

			<viewComponent>
				<form columns="3" title="Servicio">
					<fieldViewSet entitymodel="aplicativo" nameSpace="aplicativo">
						<fieldset legend="Aplicativo">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="5" editable="true" />
							<fieldView mappingTo="2" size="20" editable="false" />
							<fieldView mappingTo="6" type="select" editable="true">
								<optionValues entitymodel="tecnologia"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="3" type="select" editable="true">
								<optionValues entitymodel="servicioUTE"
									descrMappingTo="2" selectionMultiple="true">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" size="30" editable="true" />
							<fieldView mappingTo="7" type="radio" editable="true">
								<optionValues entitymodel="aplicativo"
									descrMappingTo="7" codeField="7">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>

	</service>
	
</service:service-group>

=== pdulce/pcm/BI4ONGS/WebContent/WEB-INF/services/facturacionPorColaborador.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
   xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

	<service name="GestionFactMesPorColaborador" profile="ADMINISTRADOR, CONSULTOR_UTE">
		
		<action event="update" submitError="GestionFactMesPorColaborador.update"
			submitSucces="GestionFactMesPorColaborador.update">

			<viewComponent>
				<form columns="53" title="Edicion mes facturacion">
					<fieldViewSet entitymodel="facturacionMesPorColaborador" nameSpace="facturacionMesPorColaboradorForm">
						<fieldView mappingTo="1" hidden="true"/>
						<fieldView mappingTo="2" editable="false"/>
						<fieldView mappingTo="3" type="select" editable="false">
							<optionValues entitymodel="mes"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="4" type="select" editable="false">
							<optionValues entitymodel="colaborador"
								descrMappingTo="2,3">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="10" styleCss="font-weight: bold;color: black;" editable="false"/>
						<fieldView mappingTo="5" styleCss="font-weight: bold;color: black;" editable="false"/>
						<fieldView separator="br" />
						<fieldView separator="br" />
						<fieldView mappingTo="6" styleCss="font-weight: bold;color: red;" editable="false"/>
						<fieldView mappingTo="7" styleCss="font-weight: bold;color: red;" editable="false"/>
						<fieldView mappingTo="8" styleCss="font-weight: bold;color: red;" editable="false"/>
						<fieldView mappingTo="9" styleCss="font-weight: bold;color: red;" editable="false"/>
						
					</fieldViewSet>
				</form>
				
				<grid title="Imputaciones por aplicacion de este colaborador" dependsOf="facturacionMesPorColaboradorForm" orderDirection="asc"
					defaultOrderField="facturacionMesPorColaboradoryApp.1" eventsRegistered="update"
					serviceRef="GestionFactMesPorColaboradoryApp">
					<fieldViewSet entitymodel="facturacionMesPorColaboradoryApp"
						nameSpace="facturacionMesPorColaboradoryApp">
						<fieldView mappingTo="1" hidden="true" />
						<fieldView mappingTo="3" hidden="true" />
						<fieldView mappingTo="4" type="select">
							<optionValues entitymodel="proyecto"
								descrMappingTo="2, 3">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="5" styleCss="font-weight: bold;color: black;" />		
					</fieldViewSet>
				</grid>
				
			</viewComponent>
		</action>		
		
	</service>

		
</service:service-group>

=== pdulce/pcm/BI4ONGS/WebContent/WEB-INF/services/importacionesFacturacion.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group 
	xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

	<service
		name="GestionarImportacionesFacturacion" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="query" submitError="GestionarImportacionesFacturacion.query"
		submitSucces="GestionarImportacionesFacturacion.query">

			<viewComponent>
		
				<form columns="44" title="Importaciones desde GEDEON">

				<fieldViewSet entitymodel="importacionesFacturacion"
					nameSpace="importacionesFacturacion">
					
					<fieldView mappingTo="2" type="select">
					 	<optionValues selectionMultiple="true" entitymodel="concurso"
							descrMappingTo="2">
						</optionValues>
					</fieldView>
					
					<fieldView mappingTo="3" type="select">
					 	<optionValues selectionMultiple="true" entitymodel="mes"
							descrMappingTo="2">
						</optionValues>
					</fieldView>
					<fieldView mappingTo="4" />					
					<fieldView separator="br" />
					<fieldView separator="br" />
					
					<fieldView mappingTo="5" />
					<fieldView mappingTo="7" />
					
					<fieldView separator="br" />
					
				</fieldViewSet>
			</form>

			<grid title="Listado de importaciones desde GEDEON" orderDirection="desc" defaultOrderField="ImportacionesFacturacion.4"
				eventsRegistered="create,update, delete">

				<fieldViewSet entitymodel="importacionesFacturacion"
					nameSpace="importacionesFacturacion">
					<fieldView mappingTo="1" hidden="true"/>
					<fieldView mappingTo="2" type="select">
					 	<optionValues selectionMultiple="true" entitymodel="concurso"
							descrMappingTo="2">
						</optionValues>
					</fieldView>					
					<fieldView mappingTo="3" type="select">
					 	<optionValues selectionMultiple="true" entitymodel="mes"
							descrMappingTo="2">
						</optionValues>
					</fieldView>
					<fieldView mappingTo="4" />					
					<fieldView mappingTo="5" />
					<fieldView mappingTo="6" />
					<fieldView mappingTo="7" />
				</fieldViewSet>
			</grid>

		</viewComponent>
	</action>

	<action event="create" submitError="GestionarImportacionesFacturacion.create"
		submitSucces="GestionarImportacionesFacturacion.query" strategyPre="facturacionUte.strategies.StrategyImportacionFactura">

		<viewComponent>
			<form columns="8" title="Importacion">
				<fieldViewSet entitymodel="importacionesFacturacion"
					nameSpace="importacionesFacturacion">
					<fieldset legend="Datos Importacion">
					
						<fieldView mappingTo="2" type="select">
					 	<optionValues selectionMultiple="true" entitymodel="concurso"
							descrMappingTo="2">
						</optionValues>
						</fieldView>
						
						<fieldView mappingTo="3" type="select">
						 	<optionValues selectionMultiple="true" entitymodel="mes"
								descrMappingTo="2">
							</optionValues>
						</fieldView>

						<fieldView separator="br" />
						<fieldView separator="br" />
						
						<fieldView mappingTo="4" />						
						<fieldView mappingTo="8" />
												
						
					</fieldset>
				</fieldViewSet>
			</form>
		</viewComponent>
	</action>

	<action event="delete" submitError="GestionarImportacionesFacturacion.delete"
		submitSucces="GestionarImportacionesFacturacion.query">

		<viewComponent>
			<form columns="18" title="Importacion">
				<fieldViewSet entitymodel="importacionesFacturacion"
					nameSpace="importacionesFacturacion">
					<fieldset legend="Datos Importacion">
						
						<fieldView mappingTo="1" hidden="true"/>
						<fieldView mappingTo="2" type="select" editable="false">
					 	<optionValues selectionMultiple="true" entitymodel="concurso"
							descrMappingTo="2">
						</optionValues>
						</fieldView>
						
						<fieldView mappingTo="3" type="select" editable="false">
						 	<optionValues selectionMultiple="true" entitymodel="mes"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="4" editable="false"/>
										
						<fieldView separator="br" />
						<fieldView separator="br" />
						
						<fieldView mappingTo="5" editable="false"/>
						<fieldView mappingTo="6" editable="false"/>
						<fieldView mappingTo="7" editable="false"/>
						
						<fieldView separator="br" />
						<fieldView separator="br" />
						
						<fieldView mappingTo="8" editable="false"/>

						<fieldView separator="br" />
						
					</fieldset>
				</fieldViewSet>
			</form>
		</viewComponent>
	</action>

	<action event="update" submitError="GestionarImportacionesFacturacion.update"
		submitSucces="GestionarImportacionesFacturacion.update" 
		strategyPre="facturacionUte.strategies.StrategyImportacionFactura">

		<viewComponent>
			<form columns="13" title="Edicion Importacion">
				<fieldViewSet entitymodel="importacionesFacturacion"
					nameSpace="importacionesFacturacion">
					
						<fieldView mappingTo="1" hidden="true"/>
						<fieldView mappingTo="2" type="select" editable="false">
					 	<optionValues selectionMultiple="true" entitymodel="concurso"
							descrMappingTo="2">
						</optionValues>
						</fieldView>
						
						<fieldView mappingTo="3" type="select" editable="false">
						 	<optionValues selectionMultiple="true" entitymodel="mes"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="4" editable="false"/>
										
						<fieldView separator="br" />
						<fieldView separator="br" />
						
						<fieldView mappingTo="5" editable="false"/>
						<fieldView mappingTo="6" editable="false"/>
						<fieldView mappingTo="7" editable="false"/>
						
						<fieldView separator="br" />
						<fieldView separator="br" />
						
						<fieldView mappingTo="8" editable="true"/>

						<fieldView separator="br" />
					
				</fieldViewSet>
			</form>
		</viewComponent>
	</action>


</service>

</service:service-group>
