=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://pcm.framework.org/service" 
xmlns="http://pcm.framework.org/service">
    
    <xs:element name="service-group" type="ServiceGroupType"/>
    
    <xs:complexType name="ServiceGroupType">
    	<xs:sequence>
		    <xs:element maxOccurs="unbounded" minOccurs="1" name="service" type="ServiceType"/>
		</xs:sequence>
	</xs:complexType>
    
	<xs:complexType name="profileAndNAmeInfo">
		<xs:attribute name="profile" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="ServiceType">
	  	<xs:complexContent>
	   		<xs:extension base="profileAndNAmeInfo">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="action" nillable="true" type="ActionType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ActionAttrsBaseType">
  		<xs:attribute name="id" type="xs:string"/>
  		<xs:attribute name="event" type="xs:string"/>
  		<xs:attribute name="submitError" type="xs:string"/>
  		<xs:attribute name="submitSucces" type="xs:string"/>
  		<xs:attribute name="transactional" type="xs:boolean"/>
  		<xs:attribute name="strategyPre" type="xs:string"/>
  		<xs:attribute name="strategy" type="xs:string"/>
  		<xs:attribute name="addressBook" type="xs:string"/>
  		<xs:attribute name="filterResults" type="xs:string"/>
  	</xs:complexType>
  
	<xs:complexType name="ActionType">
	  	<xs:complexContent>
	   		<xs:extension base="ActionAttrsBaseType">
		   		<xs:sequence>		    		
		    		<xs:element maxOccurs="unbounded" name="viewComponent" nillable="true" type="ComponentType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
  
  	<xs:complexType name="ComponentType">
  		<xs:sequence>
   			<xs:element maxOccurs="unbounded" minOccurs="0" name="form" nillable="true" type="FormType"/>
   			<xs:element maxOccurs="unbounded" minOccurs="0" name="grid" nillable="true" type="GridType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="FormAttrsBaseType">
		<xs:attribute name="align" type="xs:string"/>
		<xs:attribute name="columns" type="xs:integer"/>
		<xs:attribute name="title" type="xs:string"/>		
	</xs:complexType>
	
	<xs:complexType name="UserbuttonsType">
	  	<xs:sequence>
	  		<xs:element maxOccurs="unbounded" minOccurs="1" name="button" nillable="true" type="ButtonType"/>	    		
		 </xs:sequence>	   	
	</xs:complexType>
	
	
	<xs:complexType name="ButtonAttrsType">
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="onClick" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="ButtonType">
	  	<xs:complexContent>
	   		<xs:extension base="ButtonAttrsType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FormType">
	  	<xs:complexContent>
	   		<xs:extension base="FormAttrsBaseType">
		   		<xs:sequence>
		   			<xs:element maxOccurs="1" minOccurs="0" name="userbuttons" nillable="true" type="UserbuttonsType"/>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>	
	
	<xs:complexType name="GridAttrsBaseType">
		<xs:attribute name="title" type="xs:string"/>		
		<xs:attribute name="dependsOf" type="xs:string"/>
		<xs:attribute name="serviceRef" type="xs:string"/>
		<xs:attribute name="orderDirection" type="xs:string"/>
		<xs:attribute name="defaultOrderField" type="xs:string"/>
		<xs:attribute name="filterResults" type="xs:string"/>
		<xs:attribute name="eventsRegistered" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="GridType">
	  	<xs:complexContent>
	   		<xs:extension base="GridAttrsBaseType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FieldViewSetBase">
		<xs:attribute name="nameSpace" type="xs:string"/>
		<xs:attribute name="entitymodel" type="xs:string"/>
		<xs:attribute name="persist" type="xs:boolean"/>
		<xs:attribute name="order" type="xs:int"/>
	</xs:complexType>
	
	<xs:complexType name="FieldViewSetType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldViewSetBase">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="fieldset" nillable="true" type="FieldSetType"/>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="fieldView" nillable="true" type="FieldViewType"/>
		  		</xs:sequence>
	   		</xs:extension>	   		
	   	</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="FieldSetAttrBaseType">
		<xs:attribute name="legend" type="xs:string"/>
		<xs:attribute name="style" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="FieldSetType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldSetAttrBaseType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldView" nillable="true" type="FieldViewType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FieldViewTypeBase">
		<xs:attribute name="separator" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="required" type="xs:boolean"/>		
		<xs:attribute name="hidden" type="xs:boolean"/>
		<xs:attribute name="editable" type="xs:boolean"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="firstOption" type="xs:string"/>
		<xs:attribute name="size" type="xs:integer"/>
		<xs:attribute name="maxlength" type="xs:integer"/>
		<xs:attribute name="detailed" type="xs:boolean"/>
		<xs:attribute name="persistsIn" type="xs:string"/>
		<xs:attribute name="mappingTo" type="xs:integer"/>
		<xs:attribute name="relationalOpe" type="xs:string"/>
		<xs:attribute name="styleCss" type="xs:string"/>
		<xs:attribute name="formatted" type="xs:string"/>		
		<xs:attribute name="labelStyle" type="xs:string"/>	
		<xs:attribute name="default" type="xs:string"/>	
	</xs:complexType>
	
	<xs:complexType name="FieldViewType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldViewTypeBase">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="optionValues" nillable="true" type="OptionSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
  
  	<xs:complexType name="OptionSetType">
  		<xs:complexContent>
	   		<xs:extension base="OptionSetBase">
	   			<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="option" nillable="true" type="OptionType"/>
				</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
  		
  	</xs:complexType>
	
	<xs:complexType name="OptionSetBase">
  		<xs:attribute name="entitymodel" type="xs:string"/>
  		<xs:attribute name="descrMappingTo" type="xs:string"/>
  		<xs:attribute name="selectionMultiple" type="xs:boolean"/> 		  		
  		<xs:attribute name="codeField" type="xs:integer"/>
  		<xs:attribute name="editable" type="xs:boolean"/>
  	</xs:complexType>
  
    <xs:complexType name="OptionType">
    	<xs:complexContent>
	   		<xs:extension base="OptionBase">
	   		</xs:extension>
	   	</xs:complexContent>
  	</xs:complexType>
  	
  	<xs:complexType name="OptionBase">
  		<xs:attribute name="code" type="xs:string"/>
  		<xs:attribute name="title" type="xs:string"/>
  		<xs:attribute name="selected" type="xs:string"/>
  	</xs:complexType>
	  
	
</xs:schema>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/colaboradoresApps.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
   xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">
	
	<service name="GestionColaboradorApps" profile="ADMINISTRADOR, CONSULTOR_UTE">
		
		<action event="delete" submitError="GestionColaboradorApps.delete"
			submitSucces="GestionColaboradores.update"
			strategy="facturacionUte.strategies.concursos.StrategyBorrarUTsMesColabyApp">

			<viewComponent>
				<form columns="53" title="Desasignar app a colaborador">
					<fieldViewSet entitymodel="appColaborador" nameSpace="appColaborador">
						<fieldView mappingTo="1" hidden="true"/>
						
						<fieldView mappingTo="2" type="select" editable="false">
							<optionValues entitymodel="colaborador"
								descrMappingTo="2,3">
							</optionValues>
						</fieldView>

						<fieldView separator="br" />
						<fieldView separator="br" />		
						
						<fieldView mappingTo="3" type="select" editable="false">
							<optionValues entitymodel="proyecto"
								descrMappingTo="2,3">
							</optionValues>
						</fieldView>
												
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>

		<action event="create" submitError="GestionColaboradorApps.create"
			submitSucces="GestionColaboradores.update"
			strategyPre="facturacionUte.strategies.concursos.StrategySeleccionColabyApp"
			strategy="facturacionUte.strategies.concursos.StrategyGrabarUTsMesColabyApp">

			<viewComponent>
				<form columns="53" title="Asignar app a colaborador">
					<fieldViewSet entitymodel="appColaborador" nameSpace="appColaborador">
						
						<fieldView mappingTo="2" type="select">
							<optionValues entitymodel="colaborador"
								descrMappingTo="2,3">
							</optionValues>
						</fieldView>
						
						<fieldView separator="br" />
						<fieldView separator="br" />
						
						<fieldView mappingTo="3" type="select">
							<optionValues entitymodel="proyecto"
								descrMappingTo="2,3">
							</optionValues>
						</fieldView>
																
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
		
	</service>

		
</service:service-group>

=== pdulce/pcm/BI4ONGS/WebContent/WEB-INF/services/porcentajesParticipacion.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

	<service name="GestionPorcentajesParticipacion" profile="ADMINISTRADOR, CONSULTOR_UTE">
	    
	    <action event="create" submitError="GestionPorcentajesParticipacion.create"
			submitSucces="GestionPorcentajesParticipacion.update">

			<viewComponent>
				<form columns="52" title="Edicion Participacion en UTE">

					<fieldViewSet entitymodel="porcentaje_facturacion"
						nameSpace="porcentaje_facturacion">

						<fieldset legend="Porcentaje de Participacion en UTE">
							<fieldView mappingTo="1" editable="false" />
							<fieldView mappingTo="2" type="select" editable="true"><!-- name="id_empresa" 
									respeta el name del id-campo -->
								<optionValues entitymodel="empresaUTE"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="3" type="select" editable="true">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
	    
	    
		<action event="update" submitError="GestionPorcentajesParticipacion.update"
			submitSucces="GestionPorcentajesParticipacion.update">

			<viewComponent>
				<form columns="52" title="Edicion Participacion en UTE">

					<fieldViewSet entitymodel="porcentaje_facturacion"
						nameSpace="porcentaje_facturacion">

						<fieldset legend="Porcentaje de Participacion en UTE">
							<fieldView mappingTo="1" editable="false" />
							<fieldView mappingTo="2" type="select" editable="false"><!-- name="id_empresa" 
									respeta el name del id-campo -->
								<optionValues entitymodel="empresaUTE"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="3" type="select" editable="false">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>

	</service>
	
</service:service-group>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/appInitialService.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

<!-- LOGON SERVICE -->
	<service name="Authentication" profile="ADMINISTRADOR">

		<action event="submitForm" submitError="Autenticacion.submitForm"
			transactional="false" strategyPre="facturacionUte.strategies.StrategyLogin">
			<viewComponent>
				<form align="center" columns="1" title="Autenticacion">
					<fieldViewSet nameSpace="entryForm">
						
						<fieldView name="user" type="text" required="true"
							value="" size="10" maxlength="20" detailed="true" persistsIn="%session%"
							styleCss="font-weight: bold;color: #0404B4;" />
						<fieldView name="password" type="password" required="true"
							value="" size="4" maxlength="8" detailed="true"
							styleCss="font-weight: bold;color: #0404B4;" />
						<fieldView name="language" type="text" value="es_" 
							required="true" hidden="true" persistsIn="%session%"/>
							<!-- optionValues> 
								<option code="es_" title="castellano" selected="true"></option>
								<option code="en_" title="ingles"></option>
							</optionValues> -->
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
	</service>
	<!-- END OF LOGON SERVICE -->

</service:service-group>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/servicioUTE.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group 
	xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

    <service name="GestionServiciosUTE" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="query" submitError="GestionServiciosUTE.query"
			submitSucces="GestionServiciosUTE.query">

			<viewComponent>

				<form columns="3" title="Consulta servicios">

					<fieldViewSet entitymodel="servicioUTE"	nameSpace="servicioUTE">
						<fieldset legend="Servicio">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="2"/>
							<fieldView mappingTo="3" type="select" editable="true">
								<optionValues entitymodel="tecnologia" selectionMultiple="true"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="4"/>
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>

				<grid title="Listado Servicios UTE" orderDirection="asc" eventsRegistered="update, create, delete">
					<fieldViewSet entitymodel="servicioUTE"
						nameSpace="servicioUTE">
						<fieldView mappingTo="1" hidden="true"/>
						<fieldView mappingTo="2" />
						<fieldView mappingTo="3" type="select" editable="false">
							<optionValues entitymodel="tecnologia"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="4" />
					</fieldViewSet>
				</grid>

			</viewComponent>
		</action>

		<action event="delete" submitError="GestionServiciosUTE.query"
			submitSucces="GestionServiciosUTE.delete">

			<viewComponent>
				<form columns="2" title="Servicio">
					<fieldViewSet entitymodel="servicioUTE"	nameSpace="servicioUTE">
						<fieldset legend="Servicio">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="1" editable="false" />
							<fieldView mappingTo="2" editable="false" />
							<fieldView mappingTo="3" type="select" editable="false">
								<optionValues entitymodel="tecnologia"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="4" editable="false" />
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
		
		<action event="create" submitError="GestionServiciosUTE.create"
			submitSucces="GestionServiciosUTE.create">

			<viewComponent>
				<form columns="2" title="Servicio">
				
					
						<fieldViewSet entitymodel="servicioUTE"	nameSpace="servicioUTE">
							<fieldset legend="Servicio">
								<fieldView separator="br" />						
								<fieldView mappingTo="2" editable="true" />
								<fieldView mappingTo="3" type="select" editable="true">
									<optionValues entitymodel="tecnologia"
										descrMappingTo="2">
									</optionValues>
								</fieldView>
								<fieldView separator="br" />
								<fieldView separator="br" />
								<fieldView mappingTo="4" editable="true" />
								<fieldView separator="br" />
								<fieldView separator="br" />	
							</fieldset>
						</fieldViewSet>
					
				</form>
			</viewComponent>
		</action>
		
		<action event="update" submitError="GestionServiciosUTE.update"
			submitSucces="GestionServiciosUTE.update">

			<viewComponent>
				<form columns="2" title="Servicio">
					<fieldViewSet entitymodel="servicioUTE"	nameSpace="servicioUTEForm">
					
						<fieldset legend="Servicio">
							<fieldView separator="br" />	
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="2" editable="true" />
							<fieldView mappingTo="3" type="select" editable="true">
								<optionValues entitymodel="tecnologia"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="4" editable="true" />
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
				
				<grid title="Aplicaciones en cartera" dependsOf="servicioUTEForm" orderDirection="asc"
					defaultOrderField="aplicativo.1" eventsRegistered="" serviceRef="GestionServiciosUTE">
				
					<fieldViewSet entitymodel="aplicativo" nameSpace="aplicativo">
						<fieldView mappingTo="1" hidden="true" />					
						<fieldView mappingTo="2" editable="false"  />
						<fieldView mappingTo="5" editable="false"  />
						<fieldView mappingTo="3" hidden="true" />
					</fieldViewSet>
					
				</grid>
				
			</viewComponent>
		</action>

	</service>
	
</service:service-group>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/agregadoColaboradoresyApps.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">
	
	<service name="GestionImputadoColaboradoresApp" profile="ADMINISTRADOR, CONSULTOR_UTE">
		
		<action event="detail" submitError="GestionImputadoColaboradoresApp.detail"
			submitSucces="GestionImputadoColaboradoresApp.detail">
		
			<viewComponent>
				<form columns="53" title="Imputado por aplicacion">
					
					<userbuttons>
						<button link="PieChartStatsServlet" id="piechart"
							name="Piechart">
							<fieldViewSet nameSpace="piechart">
								<fieldView name="entidadGrafico" hidden="true" value="facturacionMesPorColaboradoryApp"/>
								<fieldView name="filteredByField" hidden="true" value="6=facturacionMesPorApp.1"/>
								<fieldView name="orderBy" hidden="true" value="3"/>							
								<fieldView name="fieldForGroupBy" type="select" editable="false">
									<optionValues>
										<option code="3" title="colaborador" selected="true"></option>
									</optionValues>
								</fieldView>
								<fieldView name="agregado" type="select">
									<optionValues>
										<option code="5" title="UTs realizadas"></option>
										<option code="7" title="facturado"></option>
									</optionValues>
								</fieldView>
								<fieldView name="operation" hidden="true" value="SUM"/>
							</fieldViewSet>
						</button>
					</userbuttons>
				
					<fieldViewSet entitymodel="facturacionMesPorApp"
						nameSpace="facturacionMesPorAppForm">
						<fieldset legend="Resumen mes-aplicacion">
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="2" editable="false" />
							<fieldView mappingTo="3" editable="false" type="select">
								<optionValues entitymodel="mes"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="7" editable="false" type="select">
								<optionValues entitymodel="proyecto"
									descrMappingTo="2,3">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="8" editable="false" styleCss="font-weight: bold;color: red;" />
							<fieldView mappingTo="9" editable="false" styleCss="font-weight: bold;color: red;" />
							<fieldView mappingTo="10" editable="false" styleCss="font-weight: bold;color: red;" />
						</fieldset>
					</fieldViewSet>
				</form>
				
				<grid title="Imputado/facturado por cada colaborador este mes" dependsOf="facturacionMesPorAppForm" orderDirection="asc"
					defaultOrderField="facturacionMesPorColaboradoryApp.1">
				
					<fieldViewSet entitymodel="facturacionMesPorColaboradoryApp" nameSpace="facturacionMesPorColaboradoryApp">
						<fieldView mappingTo="1" hidden="true" />
						<fieldView mappingTo="2" hidden="true" />
						<fieldView mappingTo="3" type="select" editable="false">
							<optionValues entitymodel="colaborador"
								descrMappingTo="2, 3">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="5" editable="false" styleCss="font-weight: bold;color: black;" />
						<fieldView mappingTo="7" editable="false" styleCss="font-weight: bold;color: black;" />
					</fieldViewSet>
				</grid>
				
			</viewComponent>
		</action>
		
	</service>
	
	
</service:service-group>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/empresas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

	<service name="GestionEmpresasUTE" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="query" submitError="GestionEmpresasUTE.query"
			submitSucces="GestionEmpresasUTE.query">

			<viewComponent>

				<form columns="548" title="Consulta de empresas UTE">
					<fieldViewSet entitymodel="empresaUTE" nameSpace="empresaUTE">
						<fieldset legend="Datos Empresa de Facturacion">
							<fieldView mappingTo="1" size="4" />
							<fieldView mappingTo="2" size="25" />
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="3" />
						</fieldset>
					</fieldViewSet>
				</form>
				<grid title="Listado de empresas UTE" orderDirection="asc" eventsRegistered="update,delete,create">
					<fieldViewSet entitymodel="empresaUTE" nameSpace="empresaUTE">
						<fieldView mappingTo="1" size="4" />
						<fieldView mappingTo="2" size="25" />
						<fieldView mappingTo="3" />
					</fieldViewSet>
				</grid>
			</viewComponent>
		</action>

		<action event="create" submitError="GestionEmpresasUTE.create"
			submitSucces="GestionEmpresasUTE.query">

			<viewComponent>
				<form columns="58" title="Datos Empresa">
					<fieldViewSet entitymodel="empresaUTE" nameSpace="empresaUTE">
						<fieldset legend="Datos Empresa de Facturacion">
							<fieldView mappingTo="1" size="4" hidden="true" />
							<fieldView mappingTo="2" size="25" />
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="3" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>

		<action event="delete" submitError="GestionEmpresasUTE.delete"
			submitSucces="GestionEmpresasUTE.query">

			<viewComponent>
				<form columns="58" title="Datos Empresa">
					<fieldViewSet entitymodel="empresaUTE" nameSpace="empresaUTE">
						<fieldset legend="Datos Empresa de Facturacion">
							<fieldView mappingTo="1" size="4" editable="false" />
							<fieldView mappingTo="2" size="25" editable="false" />
							<fieldView mappingTo="3" editable="false" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>

		<action event="update" submitError="GestionEmpresasUTE.update"
			submitSucces="GestionEmpresasUTE.update">

			<viewComponent>
				<form columns="58" title="Datos Empresa">
					<fieldViewSet entitymodel="empresaUTE" nameSpace="empresaUTE">
						<fieldset legend="Datos Empresa de Facturacion">
							<fieldView mappingTo="1" size="4" />
							<fieldView mappingTo="2" size="25" />
							<fieldView mappingTo="3" />
						</fieldset>
					</fieldViewSet>
				</form>
				<grid title="Listado de porcentajes de participacion en la UTE" dependsOf="empresaUTE" orderDirection="asc"
					defaultOrderField="porcentaje_facturacion.4" eventsRegistered="create,update"
					serviceRef="GestionPorcentajesParticipacion">
					<fieldViewSet entitymodel="porcentaje_facturacion"
						nameSpace="porcentaje_facturacion">
						<fieldView mappingTo="1" hidden="true" />
						<fieldView mappingTo="4" />
						<fieldView mappingTo="2" type="select" hidden="true"><!-- name="id_empresa" 
								respeta el name del id-campo -->
							<optionValues entitymodel="empresaUTE"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="3" type="select">
							<optionValues entitymodel="concurso" descrMappingTo="2">
							</optionValues>
						</fieldView>
					</fieldViewSet>
				</grid>
			</viewComponent>
		</action>

	</service>
	
	<service name="GestionPorcentajesParticipacion" profile="ADMINISTRADOR, CONSULTOR_UTE">
	    
	    <action event="create" submitError="GestionPorcentajesParticipacion.create"
			submitSucces="GestionPorcentajesParticipacion.update">

			<viewComponent>
				<form columns="52" title="Edicion Participacion en UTE">

					<fieldViewSet entitymodel="porcentaje_facturacion"
						nameSpace="porcentaje_facturacion">

						<fieldset legend="Porcentaje de Participacion en UTE">
							<fieldView mappingTo="1" editable="false" />
							<fieldView mappingTo="2" type="select" editable="true"><!-- name="id_empresa" 
									respeta el name del id-campo -->
								<optionValues entitymodel="empresaUTE"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="3" type="select" editable="true">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
	    
	    
		<action event="update" submitError="GestionPorcentajesParticipacion.update"
			submitSucces="GestionPorcentajesParticipacion.update">

			<viewComponent>
				<form columns="52" title="Edicion Participacion en UTE">

					<fieldViewSet entitymodel="porcentaje_facturacion"
						nameSpace="porcentaje_facturacion">

						<fieldset legend="Porcentaje de Participacion en UTE">
							<fieldView mappingTo="1" editable="false" />
							<fieldView mappingTo="2" type="select" editable="false"><!-- name="id_empresa" 
									respeta el name del id-campo -->
								<optionValues entitymodel="empresaUTE"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="3" type="select" editable="false">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>

	</service>
	
</service:service-group>
