=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://pcm.framework.org/service" 
xmlns="http://pcm.framework.org/service">
    
    <xs:element name="service-group" type="ServiceGroupType"/>
    
    <xs:complexType name="ServiceGroupType">
    	<xs:sequence>
		    <xs:element maxOccurs="unbounded" minOccurs="1" name="service" type="ServiceType"/>
		</xs:sequence>
	</xs:complexType>
    
	<xs:complexType name="profileAndNAmeInfo">
		<xs:attribute name="profile" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="ServiceType">
	  	<xs:complexContent>
	   		<xs:extension base="profileAndNAmeInfo">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="action" nillable="true" type="ActionType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="ActionAttrsBaseType">
  		<xs:attribute name="id" type="xs:string"/>
  		<xs:attribute name="event" type="xs:string"/>
  		<xs:attribute name="submitError" type="xs:string"/>
  		<xs:attribute name="submitSucces" type="xs:string"/>
  		<xs:attribute name="transactional" type="xs:boolean"/>
  		<xs:attribute name="strategyPre" type="xs:string"/>
  		<xs:attribute name="strategy" type="xs:string"/>
  		<xs:attribute name="addressBook" type="xs:string"/>
  		<xs:attribute name="filterResults" type="xs:string"/>
  	</xs:complexType>
  
	<xs:complexType name="ActionType">
	  	<xs:complexContent>
	   		<xs:extension base="ActionAttrsBaseType">
		   		<xs:sequence>		    		
		    		<xs:element maxOccurs="unbounded" name="viewComponent" nillable="true" type="ComponentType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
  
  	<xs:complexType name="ComponentType">
  		<xs:sequence>
   			<xs:element maxOccurs="unbounded" minOccurs="0" name="form" nillable="true" type="FormType"/>
   			<xs:element maxOccurs="unbounded" minOccurs="0" name="grid" nillable="true" type="GridType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="FormAttrsBaseType">
		<xs:attribute name="align" type="xs:string"/>
		<xs:attribute name="columns" type="xs:integer"/>
		<xs:attribute name="title" type="xs:string"/>		
	</xs:complexType>
	
	<xs:complexType name="UserbuttonsType">
	  	<xs:sequence>
	  		<xs:element maxOccurs="unbounded" minOccurs="1" name="button" nillable="true" type="ButtonType"/>	    		
		 </xs:sequence>	   	
	</xs:complexType>
	
	
	<xs:complexType name="ButtonAttrsType">
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="onClick" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="ButtonType">
	  	<xs:complexContent>
	   		<xs:extension base="ButtonAttrsType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FormType">
	  	<xs:complexContent>
	   		<xs:extension base="FormAttrsBaseType">
		   		<xs:sequence>
		   			<xs:element maxOccurs="1" minOccurs="0" name="userbuttons" nillable="true" type="UserbuttonsType"/>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>	
	
	<xs:complexType name="GridAttrsBaseType">
		<xs:attribute name="title" type="xs:string"/>		
		<xs:attribute name="dependsOf" type="xs:string"/>
		<xs:attribute name="serviceRef" type="xs:string"/>
		<xs:attribute name="orderDirection" type="xs:string"/>
		<xs:attribute name="defaultOrderField" type="xs:string"/>
		<xs:attribute name="filterResults" type="xs:string"/>
		<xs:attribute name="eventsRegistered" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="GridType">
	  	<xs:complexContent>
	   		<xs:extension base="GridAttrsBaseType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldViewSet" nillable="true" type="FieldViewSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FieldViewSetBase">
		<xs:attribute name="nameSpace" type="xs:string"/>
		<xs:attribute name="entitymodel" type="xs:string"/>
		<xs:attribute name="persist" type="xs:boolean"/>
		<xs:attribute name="order" type="xs:int"/>
	</xs:complexType>
	
	<xs:complexType name="FieldViewSetType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldViewSetBase">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="fieldset" nillable="true" type="FieldSetType"/>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="fieldView" nillable="true" type="FieldViewType"/>
		  		</xs:sequence>
	   		</xs:extension>	   		
	   	</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="FieldSetAttrBaseType">
		<xs:attribute name="legend" type="xs:string"/>
		<xs:attribute name="style" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="FieldSetType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldSetAttrBaseType">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" name="fieldView" nillable="true" type="FieldViewType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
	
	
	<xs:complexType name="FieldViewTypeBase">
		<xs:attribute name="separator" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="required" type="xs:boolean"/>		
		<xs:attribute name="hidden" type="xs:boolean"/>
		<xs:attribute name="editable" type="xs:boolean"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="firstOption" type="xs:string"/>
		<xs:attribute name="size" type="xs:integer"/>
		<xs:attribute name="maxlength" type="xs:integer"/>
		<xs:attribute name="detailed" type="xs:boolean"/>
		<xs:attribute name="persistsIn" type="xs:string"/>
		<xs:attribute name="mappingTo" type="xs:integer"/>
		<xs:attribute name="relationalOpe" type="xs:string"/>
		<xs:attribute name="styleCss" type="xs:string"/>
		<xs:attribute name="formatted" type="xs:string"/>		
		<xs:attribute name="labelStyle" type="xs:string"/>	
		<xs:attribute name="default" type="xs:string"/>	
	</xs:complexType>
	
	<xs:complexType name="FieldViewType">
	  	<xs:complexContent>
	   		<xs:extension base="FieldViewTypeBase">
		   		<xs:sequence>
		    		<xs:element maxOccurs="unbounded" minOccurs="0" name="optionValues" nillable="true" type="OptionSetType"/>
		  		</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
  
  	<xs:complexType name="OptionSetType">
  		<xs:complexContent>
	   		<xs:extension base="OptionSetBase">
	   			<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="option" nillable="true" type="OptionType"/>
				</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
  		
  	</xs:complexType>
	
	<xs:complexType name="OptionSetBase">
  		<xs:attribute name="entitymodel" type="xs:string"/>
  		<xs:attribute name="descrMappingTo" type="xs:string"/>
  		<xs:attribute name="selectionMultiple" type="xs:boolean"/> 		  		
  		<xs:attribute name="codeField" type="xs:integer"/>
  		<xs:attribute name="editable" type="xs:boolean"/>
  	</xs:complexType>
  
    <xs:complexType name="OptionType">
    	<xs:complexContent>
	   		<xs:extension base="OptionBase">
	   		</xs:extension>
	   	</xs:complexContent>
  	</xs:complexType>
  	
  	<xs:complexType name="OptionBase">
  		<xs:attribute name="code" type="xs:string"/>
  		<xs:attribute name="title" type="xs:string"/>
  		<xs:attribute name="selected" type="xs:string"/>
  	</xs:complexType>
	  
	
</xs:schema>

=== pdulce/pcm/CDDGedeoner/src/main/webapp/WEB-INF/services/appInitialService.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

<!-- LOGON SERVICE -->
	<service name="Authentication" profile="ADMINISTRADOR">

		<action event="submitForm" submitError="Authentication.submitForm"
			transactional="false" strategyPre="gedeoner.strategies.StrategyLogin">
			<viewComponent>
				<form align="center" columns="1" title="Authentication">
					<fieldViewSet nameSpace="entryForm">
						
						<fieldView name="user" type="text" required="true"
							value="" size="15" maxlength="20" detailed="true" persistsIn="%session%"
							styleCss="font-weight: bold;color: #0404B4;" />
						<fieldView name="password" type="password" required="true"
							value="" size="15" maxlength="20" detailed="true"
							styleCss="font-weight: bold;color: #0404B4;" />
						<fieldView name="language" type="text" value="es_" 
							required="true" hidden="true" persistsIn="%session%"/>
							<!-- optionValues> 
								<option code="es_" title="castellano" selected="true"></option>
								<option code="en_" title="ingles"></option>
							</optionValues> -->
						<fieldView name="style" type="radio" 
							required="true" persistsIn="%session%">
							<optionValues> 
								<option code="darkmode" title="dark style" selected="true"></option>
								<option code="whitemode" title="light style"></option>
							</optionValues>
						</fieldView>
						<fieldView name="paletaColores" type="select" size="3"
							required="true" persistsIn="%session%">
							<optionValues> 
								<option code="1" title="Paleta Colores ISM" selected="true"></option>
								<option code="2" title="Paleta Colores INSS"></option>
								<option code="3" title="Paleta Colores Libre"></option>
							</optionValues>
						</fieldView>
						
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
	</service>
	<!-- END OF LOGON SERVICE -->

</service:service-group>

=== pdulce/pcm/CDDGedeoner/src/main/webapp/WEB-INF/services/agrupacionEstudio.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group 
	xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

    <service name="GestionAgrupaEstudios" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="query" submitError="GestionAgrupaEstudios.query"
			submitSucces="GestionAgrupaEstudios.query" strategyPre="gedeoner.strategies.FiltrarPreAgrupaciones">

			<viewComponent>

				<form columns="3" title="Consulta Grupos">

					<fieldViewSet entitymodel="agrupacionEstudio"	nameSpace="agrupacionEstudio">
						<fieldset legend="Servicio">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="2"/>
							<fieldView mappingTo="3"/>
							<fieldView mappingTo="4" type="select" editable="true" size="6">
								<optionValues entitymodel="unidadOrg" selectionMultiple="true" 
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>

				<grid title="Listado Grupos" orderDirection="asc" eventsRegistered="update, create, delete">
					<fieldViewSet entitymodel="agrupacionEstudio"
						nameSpace="agrupacionEstudio">
						<fieldView mappingTo="1" hidden="true"/>
						<fieldView mappingTo="2" />
						<fieldView mappingTo="3" />
						<fieldView mappingTo="4" type="select" editable="true">
							<optionValues entitymodel="unidadOrg" descrMappingTo="2">
							</optionValues>
						</fieldView>					
					</fieldViewSet>
				</grid>

			</viewComponent>
		</action>

		<action event="delete" submitError="GestionAgrupaEstudios.query"
			submitSucces="GestionAgrupaEstudios.delete">

			<viewComponent>
				<form columns="2" title="Grupo">
					<fieldViewSet entitymodel="agrupacionEstudio"	nameSpace="agrupacionEstudio">
						<fieldset legend="Servicio">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="1" editable="false" />
							<fieldView mappingTo="2" editable="false" />
							<fieldView mappingTo="3" editable="false" />
							<fieldView mappingTo="4" type="select" editable="false"  size="6">
								<optionValues entitymodel="unidadOrg" descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
		
		<action event="create" submitError="GestionAgrupaEstudios.create"
			submitSucces="GestionAgrupaEstudios.create">

			<viewComponent>
				<form columns="2" title="Grupo">
				
					
						<fieldViewSet entitymodel="agrupacionEstudio"	nameSpace="agrupacionEstudio">
							<fieldset legend="Servicio">
								<fieldView separator="br" />						
								<fieldView mappingTo="2" editable="true" />
								<fieldView mappingTo="3" editable="true" />
								<fieldView mappingTo="4" type="select" editable="true"  size="6">
									<optionValues entitymodel="unidadOrg" descrMappingTo="2">
									</optionValues>
								</fieldView>
								<fieldView separator="br" />
								<fieldView separator="br" />	
							</fieldset>
						</fieldViewSet>
					
				</form>
			</viewComponent>
		</action>
		
		<action event="update" submitError="GestionAgrupaEstudios.update"
			submitSucces="GestionAgrupaEstudios.update">

			<viewComponent>
				<form columns="2" title="Grupo">
					<fieldViewSet entitymodel="agrupacionEstudio" nameSpace="agrupacionEstudioForm">
					
						<fieldset legend="Servicio">
							<fieldView separator="br" />	
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="2" editable="true" />
							<fieldView mappingTo="3" editable="true" />
							<fieldView mappingTo="4" type="select" editable="true"  size="6">
								<optionValues entitymodel="unidadOrg" descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
				
				<grid title="Aplicaciones en cartera" dependsOf="agrupacionEstudioForm" orderDirection="asc"
					defaultOrderField="aplicativo.1" eventsRegistered="" serviceRef="GestionAgrupaEstudios">
				
					<fieldViewSet entitymodel="aplicativo" nameSpace="aplicativo">
						<fieldView mappingTo="1" hidden="true" />					
						<fieldView mappingTo="2" editable="false"  />
						<fieldView mappingTo="5" editable="false"  />
						<fieldView mappingTo="3" hidden="true" />
					</fieldViewSet>
					
				</grid>
				
			</viewComponent>
		</action>

	</service>
	
</service:service-group>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/agregadosMesServicioContratoDpto.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

	<service name="GestionAgregadosMesDpto" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="detail" submitError="GestionAgregadosMesDpto.detail"
			submitSucces="GestionAgregadosMesDpto.detail">

			<viewComponent>
				<form columns="51" title="Datos facturacion por dpto. y mes">
					<fieldViewSet entitymodel="facturacionMesPorDpto"
						nameSpace="facturacionMesPorDptoForm">

						<fieldset legend="Resumen mes">
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="2" editable="false"/>
							<fieldView mappingTo="3" editable="false" type="select">
								<optionValues entitymodel="mes"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" editable="false" type="select">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>							
							<fieldView mappingTo="5" editable="false" type="select">
								<optionValues entitymodel="servicio"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="6" editable="false" type="select">
								<optionValues entitymodel="departamento"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							
							<fieldView separator="br" />
							<fieldView separator="br" />
							
							<fieldView mappingTo="9" editable="false"/>
							<fieldView mappingTo="7" editable="false"/>
							<fieldView mappingTo="8" editable="false"/>
							
						</fieldset>
					</fieldViewSet>
				</form>
				
				<grid title="Listado de mensualidades de facturacion por aplicacion" dependsOf="facturacionMesPorDptoForm" orderDirection="asc"
					defaultOrderField="facturacionMesPorApp.1" eventsRegistered="detail"
					serviceRef="GestionImputadoColaboradoresApp">
					<fieldViewSet entitymodel="facturacionMesPorApp"
						nameSpace="facturacionMesPorApp">
						<fieldView mappingTo="1" hidden="true" />
						<fieldView mappingTo="2" />
						<fieldView mappingTo="3" type="select">
							<optionValues entitymodel="mes"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="7" type="select">
							<optionValues entitymodel="proyecto"
								descrMappingTo="2,3">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="8" styleCss="font-weight: bold;color: red;" />
						<fieldView mappingTo="9" styleCss="font-weight: bold;color: red;" />
						<fieldView mappingTo="10" styleCss="font-weight: bold;color: red;" />
					</fieldViewSet>
				</grid>
				
			</viewComponent>
		</action>
	</service>
	
	
</service:service-group>

=== pdulce/pcm/CDDGedeoner/src/main/webapp/WEB-INF/services/subdirecciones.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group 
	xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">

    <service name="GestionSubdirecciones" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="query" submitError="GestionSubdirecciones.query"
			submitSucces="GestionSubdirecciones.query">

			<viewComponent>

				<form columns="3" title="Consulta Áreas">

					<fieldViewSet entitymodel="subdireccion" nameSpace="subdireccion">
						<fieldset legend="subdireccion">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="2"  size="25"/>							
							<fieldView mappingTo="3"  size="45"/>
							<fieldView mappingTo="4" type="select" editable="true" size="6">
								<optionValues entitymodel="unidadOrg" selectionMultiple="true" 
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>

				<grid title="Listado Áreas" orderDirection="asc" eventsRegistered="update, create, delete">
					<fieldViewSet entitymodel="subdireccion"
						nameSpace="subdireccion">
						<fieldView mappingTo="1" hidden="true"/>
						<fieldView mappingTo="2" />
						<fieldView mappingTo="3" />						
						<fieldView mappingTo="4" type="select" editable="true">
							<optionValues entitymodel="unidadOrg" descrMappingTo="2">
							</optionValues>
						</fieldView>					
					</fieldViewSet>
				</grid>

			</viewComponent>
		</action>

		<action event="delete" submitError="GestionSubdirecciones.query"
			submitSucces="GestionSubdirecciones.delete">

			<viewComponent>
				<form columns="2" title="Área">
					<fieldViewSet entitymodel="subdireccion"	nameSpace="subdireccion">
						<fieldset legend="subdireccion">
							<fieldView separator="br" />
							<fieldView separator="br" />
							<fieldView mappingTo="1" editable="false"   size="15"/>
							<fieldView mappingTo="2" editable="false"   size="25"/>
							<fieldView mappingTo="3" editable="false"   size="45"/>
							<fieldView mappingTo="4" type="select" editable="false" size="6">
								<optionValues entitymodel="unidadOrg" descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
			</viewComponent>
		</action>
		
		<action event="create" submitError="GestionSubdirecciones.create"
			submitSucces="GestionSubdirecciones.create">

			<viewComponent>
				<form columns="2" title="Área">
				
					
						<fieldViewSet entitymodel="subdireccion"	nameSpace="subdireccion">
							<fieldset legend="subdireccion">
								<fieldView separator="br" />						
								<fieldView mappingTo="2" editable="true"   size="25"/>
								<fieldView mappingTo="3" editable="true"   size="45"/>
								<fieldView mappingTo="4" type="select" editable="true" size="6">
									<optionValues entitymodel="unidadOrg" descrMappingTo="2">
									</optionValues>
								</fieldView>
								<fieldView separator="br" />	
							</fieldset>
						</fieldViewSet>
					
				</form>
			</viewComponent>
		</action>
		
		<action event="update" submitError="GestionSubdirecciones.update"
			submitSucces="GestionSubdirecciones.update">

			<viewComponent>
				<form columns="2" title="Área">
					<fieldViewSet entitymodel="subdireccion"	nameSpace="subdireccForm">
					
						<fieldset legend="subdireccion">
							<fieldView separator="br" />	
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="2" editable="true"   size="25"/>
							<fieldView mappingTo="3" editable="true"   size="45"/>
							<fieldView mappingTo="4" type="select" editable="true" size="6">
								<optionValues entitymodel="unidadOrg" descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView separator="br" />
						</fieldset>
					</fieldViewSet>
				</form>
				
				<grid title="Subáreas" dependsOf="subdireccForm" orderDirection="asc"
					defaultOrderField="servicio.2" eventsRegistered="" serviceRef="GestionSubdirecciones">
				
					<fieldViewSet entitymodel="servicio" nameSpace="servicio">
						<fieldView mappingTo="1" hidden="true" />					
						<fieldView mappingTo="2" editable="false"  />
						<fieldView mappingTo="3" hidden="true" />
						<fieldView mappingTo="4" hidden="true"  />						
					</fieldViewSet>
					
				</grid>
												
			</viewComponent>
		</action>

	</service>
	
</service:service-group>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/agregadosMesContrato.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">
	
	<service name="GestionAgregadosMesConcurso" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="detail" submitError="GestionAgregadosMesConcurso.detail"
			submitSucces="GestionAgregadosMesConcurso.detail">

			<viewComponent>
				<form columns="51" title="Datos facturacion concurso">
					<fieldViewSet entitymodel="facturacionMesPorConcurso"
						nameSpace="facturacionMesPorConcursoForm">

						<fieldset legend="Resumen mes">
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="2" editable="false"/>
							<fieldView mappingTo="3" editable="false" type="select">
								<optionValues entitymodel="mes"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" editable="false" type="select">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>							
							
							<fieldView mappingTo="5" editable="false" styleCss="font-weight: bold;color: blue;"/>
							<fieldView separator="br" />
							<fieldView separator="br" />
							
							<fieldView mappingTo="9" editable="false"/>
							<fieldView mappingTo="6" editable="false"/>
							<fieldView mappingTo="7" editable="false"/>
							<fieldView mappingTo="8" editable="false" styleCss="font-weight: bold;color: red;" />
							
						</fieldset>
					</fieldViewSet>
				</form>
				
				<grid title="Listado de mensualidades de facturacion por servicio" dependsOf="facturacionMesPorConcursoForm" orderDirection="asc"
					defaultOrderField="facturacionMesPorServicio.1" eventsRegistered="detail"
					serviceRef="GestionAgregadosMesServicio">
					<fieldViewSet entitymodel="facturacionMesPorServicio"
						nameSpace="facturacionMesPorServicio">
						<fieldView mappingTo="1" hidden="true" />
						<fieldView mappingTo="2" />
						<fieldView mappingTo="3" type="select">
							<optionValues entitymodel="mes"
								descrMappingTo="2">
							</optionValues>
						</fieldView>						
						<fieldView mappingTo="5" type="select">
							<optionValues entitymodel="servicio"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="6" styleCss="font-weight: bold;color: black;" />
						<fieldView mappingTo="7" styleCss="font-weight: bold;color: red;" />
						<fieldView mappingTo="8" styleCss="font-weight: bold;color: red;" />
					</fieldViewSet>
				</grid>
				
			</viewComponent>
		</action>

	</service>

	
</service:service-group>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/services/agregadosMesServicioDeContrato.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<service:service-group
xmlns:service="http://pcm.framework.org/service"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/service services.xsd">
	
	<service name="GestionAgregadosMesServicio" profile="ADMINISTRADOR, CONSULTOR_UTE">

		<action event="detail" submitError="GestionAgregadosMesServicio.detail"
			submitSucces="GestionAgregadosMesServicio.detail">

			<viewComponent>
				<form columns="51" title="Datos facturacion por servicio y mes">
					<fieldViewSet entitymodel="facturacionMesPorServicio"
						nameSpace="facturacionMesPorServicioForm">

						<fieldset legend="Resumen mes servicio">
							<fieldView mappingTo="1" hidden="true" />
							<fieldView mappingTo="2" editable="false"/>
							<fieldView mappingTo="3" editable="false" type="select">
								<optionValues entitymodel="mes"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="4" editable="false" type="select">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							<fieldView mappingTo="5" editable="false" type="select">
								<optionValues entitymodel="servicio"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
							
							<fieldView separator="br" />
							<fieldView separator="br" />
							
							<fieldView mappingTo="8" editable="false"/>
							<fieldView mappingTo="6" editable="false"/>
							<fieldView mappingTo="7" editable="false"/>
							
						</fieldset>
					</fieldViewSet>
				</form>
				
				<grid title="Listado de mensualidades de facturacion por departamento" dependsOf="facturacionMesPorServicioForm" orderDirection="asc"
					defaultOrderField="facturacionMesPorDpto.1" eventsRegistered="detail"
					serviceRef="GestionAgregadosMesDpto">
					<fieldViewSet entitymodel="facturacionMesPorDpto"
						nameSpace="facturacionMesPorDpto">
						<fieldView mappingTo="1" hidden="true" />
						<fieldView mappingTo="2" />
						<fieldView mappingTo="3" type="select">
							<optionValues entitymodel="mes"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="4" editable="false" type="select">
								<optionValues entitymodel="concurso"
									descrMappingTo="2">
								</optionValues>
							</fieldView>
						<fieldView mappingTo="6" type="select">
							<optionValues entitymodel="departamento"
								descrMappingTo="2">
							</optionValues>
						</fieldView>
						<fieldView mappingTo="7" styleCss="font-weight: bold;color: red;" />
						<fieldView mappingTo="8" styleCss="font-weight: bold;color: red;" />
						<fieldView mappingTo="9" styleCss="font-weight: bold;color: red;" />
					</fieldViewSet>
				</grid>
				
			</viewComponent>
		</action>

	</service>

	
</service:service-group>
