=== pdulce/pcm/contextPropModel/src/META-INF/entities.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://pcm.framework.org/ent" xmlns="http://pcm.framework.org/ent">
            
    <xs:element name="entities" type="EntitiesType"/>
  
	<xs:complexType name="EntitiesType">
	  	<xs:sequence>
     		<xs:element maxOccurs="unbounded" name="entity" nillable="false" type="EntityType"/>
   		</xs:sequence>
	</xs:complexType>
   	
   	
   	<xs:complexType name="EntityType">
		<xs:sequence>
			<xs:element name="entityname" type="xs:string"/>
			<xs:element maxOccurs="unbounded" name="field" nillable="true" type="FieldType"/>
		</xs:sequence>	     
	</xs:complexType>
  
  <xs:complexType name="FieldType">
  	<xs:attribute name="mappingTo" type="xs:integer"/>
   	<xs:attribute name="name" type="xs:string"/>
   	<xs:attribute name="default" type="xs:string"/>
   	<xs:attribute name="type" type="xs:string"/>
   	<xs:attribute name="length" type="xs:integer"/>
   	<xs:attribute name="belongsPK" type="xs:boolean"/>
   	<xs:attribute name="passwordType" type="xs:boolean"/>
   	<xs:attribute name="autoinc" type="xs:boolean"/>   	
   	<xs:attribute name="required" type="xs:boolean"/>
   	<xs:attribute name="minvalue" type="xs:integer"/>
   	<xs:attribute name="maxvalue" type="xs:integer"/>
   	<xs:attribute name="fkParentEntities" type="xs:string"/>
   	<xs:attribute name="fkParentFields" type="xs:integer"/>
  </xs:complexType>
   	
  
</xs:schema>

=== pdulce/pcm/SeguimientoProyectos/WebContent/resources/Regression_Estimación-Analysis_02.00_archivos/entities.xml
<?xml version="1.0" encoding="UTF-8"?>

<ent:entities xmlns:ent="http://pcm.framework.org/ent"
			  xmlns:xs="http://www.w3.org/2001/XMLSchema"
			  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:schemaLocation="http://pcm.framework.org/ent entities.xsd">
  
  <entity>
    <entityname>rol</entityname>
    <field mappingTo="1" name="id" type="long" length="11" belongsPK="true" required="true" autoinc="true"/>
    <field mappingTo="2" name="nombre" type="string" length="25" required="true"/>
  </entity>
    
   <entity>
    <entityname>administrador</entityname>
    <field mappingTo="1" name="id" type="long" length="11" belongsPK="true" required="true" autoinc="true"/>
    <field mappingTo="2" name="login_name" type="string" length="20" required="true"/>
    <field mappingTo="3" name="password" type="string" length="20" required="true" passwordType="true"/>
    <field mappingTo="4" name="profile" type="long" length="11" required="true"
    	fkParentEntities="rol" fkParentFields="1"/>
    <field mappingTo="5" name="nombreCompleto" type="string" length="100" required="true"/>
  </entity>
  
  <entity>
    <entityname>invertia_import</entityname>
    <field mappingTo="1" name="identificador" type="long" length="6" belongsPK="true" autoinc="true"/>
    <field mappingTo="2" name="grupo" type="string" length="25" required="false"/>
    <field mappingTo="3" name="num_entradas" type="integer" length="6" required="false"/>
    <field mappingTo="4" name="fec_importacion" type="date" length="10" required="false"/>
    <field mappingTo="5" name="excel_file" type="blob" length="25" required="true"/>
    <field mappingTo="6" name="filename" type="string" length="50" required="false"/>
  </entity>
  
  <entity>
    <entityname>invertia_data</entityname>
    <field mappingTo="1" name="IDENTIFICADOR" type="long" length="10" belongsPK="true" autoinc="true"/>
    <field mappingTo="2" name="GRUPO" type="string" length="25" required="true"/>
    <field mappingTo="3" name="FECHA" type="date" length="10" required="true"/>
    <field mappingTo="4" name="LAST_PUNTAJE" type="double" length="10" required="true"/>
    <field mappingTo="5" name="INICIAL_PUNTAJE" type="double" length="10" required="true"/>
    <field mappingTo="6" name="PORCENTAJE_DIF" type="double" length="8" required="true"/>
    <field mappingTo="7" name="MAX_PUNTAJE" type="double" length="10" required="true"/>
    <field mappingTo="8" name="MIN_PUNTAJE" type="double" length="10" required="true"/>
    <field mappingTo="9" name="VOLUMEN" type="long" length="14" required="true"/>
    <field mappingTo="10" name="FEC_IMPORTACION" type="date" length="10" required="false"/>
    <field mappingTo="11" name="ANYO_MES" type="string" length="7" required="false"/>
  </entity>
  
  <entity>
    <entityname>importacionesGEDEON</entityname>
    <field mappingTo="1" name="rochade" type="string" length="5" belongsPK="true" required="true"/>
    <field mappingTo="2" name="filename" type="string" length="100" required="false"/>
    <field mappingTo="3" name="numEntradas" type="integer" length="6" required="false"/>
    <field mappingTo="4" name="fechaImportacion" type="date" length="10" required="false"/>
    <field mappingTo="5" name="excelFile" type="blob" length="25" required="true"/>
    <field mappingTo="6" name="servicioDestino" type="string" length="20" required="true"/>    
  </entity>
  
  <entity>
    <entityname>peticiones</entityname>
    <field mappingTo="1" name="id" type="string" length="10" belongsPK="true" required="true"/>
    <field mappingTo="2" name="Titulo" type="string" length="500" required="false"/>
    <field mappingTo="3" name="Descripcion" type="string" length="1000" required="false"/>
    <field mappingTo="4" name="Observaciones" type="string" length="1000" required="false"/>
    <field mappingTo="5" name="Usuario_creador" type="string" length="80" required="false"/>
    <field mappingTo="6" name="Solicitante" type="string" length="200" required="false"/>
    <field mappingTo="7" name="Estado" type="string" length="50" required="false"/>        
    <field mappingTo="8" name="Entidad_origen" type="string" length="100" required="false"/>
    <field mappingTo="9" name="Unidad_origen" type="long" length="11" required="false"
    	fkParentEntities="subdireccion" fkParentFields="1"/>
    <field mappingTo="10" name="Area_origen" type="long" length="11" required="false"
    	fkParentEntities="servicio" fkParentFields="1"/>
    <field mappingTo="11" name="Centro_destino" type="string" length="100" required="false"/>
    <field mappingTo="12" name="Area_destino" type="string" length="100" required="false"/>    
    <field mappingTo="13" name="Tipo" type="string" length="50" required="false"/>        
    <field mappingTo="14" name="Tipo_inicial" type="string" length="50" required="false"/>
    <field mappingTo="15" name="Urgente" type="string" length="25" required="false"/>
    <field mappingTo="16" name="Prioridad" type="string" length="25" required="false"/>
    <field mappingTo="17" name="Fecha_de_alta" type="date" length="10" required="false"/>
    <field mappingTo="18" name="Fecha_de_tramitacion" type="date" length="10" required="false"/>
    <field mappingTo="19" name="Fecha_de_necesidad" type="date" length="10" required="false"/>     
    <field mappingTo="20" name="Fecha_fin_de_desarrollo" type="date" length="10" required="false"/>
    <field mappingTo="21" name="Fecha_de_finalizacion" type="date" length="10" required="false"/>
    <field mappingTo="22" name="Des_fecha_prevista_inicio" type="date" length="10" required="false"/>
    <field mappingTo="23" name="Des_fecha_prevista_fin" type="date" length="10" required="false"/>
    <field mappingTo="24" name="Des_fecha_real_inicio" type="date" length="10" required="false"/>
    <field mappingTo="25" name="Des_fecha_real_fin" type="date" length="10" required="false"/>
    <field mappingTo="26" name="Proyecto_ID" type="string" length="10" required="true"/>        
    <field mappingTo="27" name="Proyecto_Name" type="string" length="150" required="false"/>    
    <field mappingTo="28" name="Horas_estimadas_actuales" type="double" length="10" required="false"/>
    <field mappingTo="29" name="Horas_reales" type="double" length="10" required="false"/>
    <field mappingTo="30" name="anyo_mes" type="string" length="7" required="false"/>
    <field mappingTo="31" name="fecha_export" type="date" length="10" required="false"/>
    <field mappingTo="32" name="version_analysis" type="string" length="20" required="false"/>
    <field mappingTo="33" name="servicio_atiende_pet" type="string" length="20" required="false"/>
    <field mappingTo="34" name="con_entrega" type="boolean" length="1" required="false"/>
    <field mappingTo="35" name="id_entrega_asociada" type="string" length="10" required="false"/>
    <field mappingTo="36" name="pets_relacionadas" type="string" length="250" required="false"/>
    <field mappingTo="37" name="fecha_estado_modif" type="timestamp" length="19" required="false"/>
    <field mappingTo="38" name="tipo_fecha" type="integer" length="2" required="false"/>
    <field mappingTo="39" name="fecha_informe" type="date" length="10" required="false"/>
    <field mappingTo="40" name="estado_informe" type="string" length="100" required="false"/>
    <field mappingTo="41" name="entorno" type="long" length="11" required="false" 
       fkParentEntities="tipoAplicacion" fkParentFields="1"/>
    <field mappingTo="42" name="Horas_estimadas_iniciales" type="double" length="10" required="false"/>
    <field mappingTo="43" name="fecha_validada_CD" type="date" length="10" required="false"/>    
</entity>

<entity>
    <entityname>tiposTareas</entityname>
    <field mappingTo="1" name="id" type="long" length="11" belongsPK="true" required="true"/>    
    <field mappingTo="2" name="nombre" type="string" length="100" required="false"/>	
</entity>

<entity>
    <entityname>tareasPeticion</entityname>
    <field mappingTo="1" name="id" type="long" length="11" belongsPK="true" required="true"/>
    <field mappingTo="2" name="id_tareaGEDEON" type="string" length="20" required="false"/>
    <field mappingTo="3" name="id_peticion" type="string" length="10" required="false" 
       fkParentEntities="peticiones" fkParentFields="1"/>
    <field mappingTo="4" name="id_tipotarea" type="long" length="11" required="false" 
       fkParentEntities="tiposTareas" fkParentFields="1"/>
    <field mappingTo="5" name="nombre" type="string" length="200" required="false"/>
    <field mappingTo="6" name="horas_imputadas" type="double" length="10" required="false"/>
    <field mappingTo="7" name="horas_previstas" type="double" length="10" required="false"/>   
 	<field mappingTo="8" name="fecha_inicio_previsto" type="date" length="10" required="false"/>
 	<field mappingTo="9" name="fecha_fin_previsto" type="date" length="10" required="false"/>
    <field mappingTo="10" name="fecha_inicio_real" type="date" length="10" required="false"/>
    <field mappingTo="11" name="fecha_fin_real" type="date" length="10" required="false"/>
    <field mappingTo="12" name="Fecha_de_alta" type="date" length="10" required="false"/>
    <field mappingTo="13" name="Fecha_de_tramitacion" type="date" length="10" required="false"/>
    <field mappingTo="14" name="anyo_mes" type="string" length="7" required="false"/>
</entity>

	
<entity>
    <entityname>estudiosPeticiones</entityname>
    <field mappingTo="1" name="id" type="long" length="11" belongsPK="true" required="true" autoinc="true"/>
    <field mappingTo="2" name="tituloEstudio" type="string" length="250" required="false"/>    
    <field mappingTo="3" name="id_entorno" type="long" length="11" required="true" 
	    fkParentEntities="tecnologia" fkParentFields="1"/>  
	<field mappingTo="4" name="aplicaciones" type="string" length="500" required="false"/>	
	<field mappingTo="5" name="fecha_inicio_estudio" type="date" length="10" required="false"/>
