=== pdulce/pcm/contextPropModel/src/META-INF/metamodel.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://pcm.framework.org/metamodel" xmlns="http://pcm.framework.org/metamodel">
            
    <xs:element name="application" type="AppType"/>
  
	<xs:complexType name="AppType">
   		<xs:sequence>
   			<xs:element maxOccurs="1" name="configuration" nillable="false" type="ConfigurationType"/>
   			<xs:element maxOccurs="1" name="profiles" nillable="false" type="ProfilesType"/>		    		
			<xs:element name="logo" nillable="true" type="LogoType"/>
			<xs:element name="foot" nillable="true" type="FootType"/>
			<xs:element name="tree" nillable="true" type="TreeType"/>
  		</xs:sequence>
	</xs:complexType>
   	
   	<xs:complexType name="ConfigurationType">
   		<xs:complexContent>
    		<xs:extension base="serverPathInfoType">   	
   				<xs:sequence>
					<xs:element maxOccurs="unbounded" name="entry" nillable="false" type="EntryConfigType"/>
   				</xs:sequence>
	   		</xs:extension>
	   	</xs:complexContent>
	</xs:complexType>
   		
   		
	<xs:complexType name="serverPathInfoType">
		<xs:attribute name="serverPath" type="xs:string"/>
	</xs:complexType>
   		
   	
   	<xs:complexType name="EntryConfigType">
		<xs:attribute name="key" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
	</xs:complexType>
   	
   	<xs:complexType name="LogoType">
		<xs:attribute name="content" type="xs:string"/>
		<xs:attribute name="width" type="xs:string"/>
		<xs:attribute name="height" type="xs:string"/>
		<xs:attribute name="alt" type="xs:string"/>
		<xs:attribute name="uri" type="xs:string"/>
	</xs:complexType>
   	
   	
   	<xs:complexType name="profileAndNAmeInfo">
		<xs:attribute name="profile" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
   	
   	<xs:complexType name="ProfilesType">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="profile" nillable="true" type="ProfileType"/>
		</xs:sequence>
	</xs:complexType>
  
  <xs:complexType name="ProfileType">
		<xs:attribute name="name" type="xs:string"/>		
		<xs:attribute name="description" type="xs:string"/>		
	</xs:complexType>
  
	<xs:complexType name="MenuType">
		<xs:sequence>   
	 		<xs:element maxOccurs="unbounded" name="menu_entry" nillable="true" type="MenuEntryType"/>
	 	</xs:sequence>
	</xs:complexType>
	
	 <xs:complexType name="MenuEntryType">
		<xs:complexContent>
    		<xs:extension base="profileAndNAmeInfo">
    			<xs:attribute name="action" type="xs:string"/>
    		</xs:extension>    		
    	</xs:complexContent>
	</xs:complexType>
	 	
	<xs:complexType name="FootType">
		<xs:attribute name="text" type="xs:string"/>
		<xs:attribute name="link" type="xs:string"/>
	</xs:complexType>
	
	
	<xs:complexType name="TreeType">
		<xs:complexContent>
    		<xs:extension base="profileAndNAmeInfo">		
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="LEAF" nillable="true" type="LEAFType"/>	
	 				<xs:element maxOccurs="unbounded" minOccurs="0" name="FOLDER" nillable="true" type="FOLDERType"/>
	 			</xs:sequence>
	 		</xs:extension>
	 	</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="FOLDERType">
		<xs:complexContent>
    		<xs:extension base="profileAndNAmeInfo">			
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="LEAF" nillable="true" type="LEAFType"/>						
					<xs:element maxOccurs="unbounded" minOccurs="0" name="FOLDER" nillable="true" type="FOLDERType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="LEAFType">
		<xs:attribute name="link" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	
	
  	
  	
 	
</xs:schema>

=== pdulce/pcm/SeguimientoProyectos/WebContent/WEB-INF/metamodel.xml
<?xml version="1.0" encoding="UTF-8"?>

<app:application xmlns:app="http://pcm.framework.org/metamodel"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://pcm.framework.org/metamodel metamodel.xsd">

	<configuration serverPath="C:\\apache-tomcat-7.0.85\\default">
		<entry key="appTitle" value="Seguimiento de Proyectos"></entry>
		<entry key="auditActivated" value="false"></entry>
		<entry key="template" value="/jsp/template.jsp"></entry>
		<entry key="datasourceAccess" value="JDBC"></entry> <!--valores: [JNDI|JDBC] -->
		<entry key="datasourceImpl" value="pcm.context.logicmodel.persistence.SqliteDAOSQLImpl"></entry>
		<entry key="entitiesDictionary" value="/WEB-INF/entities.xml"></entry>
		<entry key="driver-class" value="org.sqlite.JDBC"></entry>
		<entry key="url-connection" value="jdbc:sqlite:"></entry>
		<entry key="dbPort" value="-1"></entry><!-- SQLite no requiere puerto -->
		<entry key="esquemaDDBB" value="#serverPath#\\data\\sqlite\\factUTEDBLite.db"></entry>
		<entry key="dbUserName" value=""></entry><!-- SQLite no requiere user -->
		<entry key="dbPassword" value=""></entry><!-- SQLite no requiere passwd -->		
		<entry key="pageSize" value="25"></entry>		
		<entry key="logAppFile"
			value="#serverPath#\\log\\logSeguimientoUTE.xml"></entry>
		<entry key="downloadDir"
			value="#serverPath#\\downloads\\"></entry>
		<entry key="uploadDir"
			value="#serverPath#\\uploads\\"></entry>
	</configuration>

	<profiles>
		<profile name="ADMINISTRADOR"
			description="Usuario administrador" />
		<profile name="CONSULTOR_UTE"
			description="Usuario consultor" />
		<profile name="CONSULTOR_UTE"
			description="Usuario invitado, con acceso a ver colaboradores" />
		<profile name="ANALISIS_TEAM" description="Analista del equipo del CDINSS" />
	</profiles>

	<logo content="img/logoPCM.PNG" width="202" height="72" alt="Inicio" uri="SeguimientoProyectos"/>

	<foot text="Seguimiento Proyectos v&lt;b&gt;&lt;i&gt;01.05&lt;/i&gt;&lt;/b&gt; [14/01/2020]" link="SeguimientoProyectos" />

	<tree profile="ADMINISTRADOR" name="tree">

		<FOLDER profile="ADMINISTRADOR" name="Config.">
			<LEAF link="exec=Configuration" name="Configuraciones" />
			<LEAF link="event=GestionEntidades.query#entityName=rol" name="Roles" />
			<LEAF link="event=GestionUsuarios.query" name="Usuarios" />
			<LEAF link="event=GestionEntidades.query#entityName=tipoAplicacion" name="Technologies" />
			<LEAF link="event=GestionEntidades.query#entityName=mes" name="Meses" />
		</FOLDER>
		
		<FOLDER profile="ADMINISTRADOR, CONSULTOR_UTE" name="Mapa organizativo">
			<LEAF link="event=GestionEntidades.query#entityName=unidadOrg" name="Organismos" />
			<LEAF link="event=GestionEntidades.query#entityName=edificio" name="Centros" />
			<LEAF link="event=GestionEntidades.query#entityName=subdireccion" name="Subdirecciones" />
			<LEAF link="event=GestionResponsablesCentros.query" name="Responsables" />
			<LEAF link="event=GestionServicios.query" name="Servicios" />
			<LEAF link="event=GestionProyectos.query" name="Aplicaciones" />
			<LEAF link="event=GestionColaboradores.query" name="Colaboradores" />
		</FOLDER>
		
		<FOLDER profile="ADMINISTRADOR, CONSULTOR_UTE" name="UTEs">
			<LEAF link="event=GestionConcursos.query" name="Contratos/Lotes" />
			<LEAF link="event=GestionEmpresasUTE.query" name="Empresas" />
			<LEAF link="event=GestionEntidades.query#entityName=categoria_profesional" name="Tarifas por perfil" />
			<LEAF link="event=GestionEntidades.query#entityName=responsabilidad" name="Atribuciones" />
		</FOLDER>

		<FOLDER profile="ADMINISTRADOR, CONSULTOR_UTE"
			name="Seguimiento">
			<LEAF link="event=ConsultaPeticionesGEDEON.query" name="GEDEON(es)" />
			<LEAF link="event=InformePeticionesSG.query" name="Demanda SGD" />
		</FOLDER>
		
		<FOLDER profile="ADMINISTRADOR"
				name="Importaciones GEDEON">
			<LEAF link="event=GestionarImportacionesGEDEON.query" name="Importaciones" />
		</FOLDER>
					
		<!-- FOLDER profile="ADMINISTRADOR"	name="Cotizaciones Bolsa">
			<LEAF link="event=ConsultaPeticionesDatosInvertia.query" name="Consultas/estad." />
			<LEAF link="/SeguimientoProyectos/LauncherUtility?exec=allInfoBolsa" name="Actualizar autom. Valores" />
		</FOLDER>
		<FOLDER profile="ADMINISTRADOR"	name="Bolsa Cartera Valores">
			<LEAF link="/SeguimientoProyectos/LauncherUtility?exec=myInfoBolsa" name="Valores actuales en Mi Cartera" />
		</FOLDER> -->

	</tree>
	
	
</app:application>
